version: "3.0"
services:
  test:
    image: circleci/openjdk:9-jdk
    working_dir: /code
    environment:
      - DRIVEBACKUP_CLIENT_SECRETS=${DRIVEBACKUP_CLIENT_SECRETS}
    volumes:
      - .:/code
      - ./.m2/:/home/circleci/.m2
      - ./.credentials/:/home/circleci/.credentials
    ports:
      - '30001:30001'
    command: mvn test
