version: 2
jobs:
  build:

    working_directory: ~/drivebackup

    docker:
      - image: circleci/openjdk:8-jdk

    steps:

      - checkout

      - restore_cache:
          key: drivebackup-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: drivebackup-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
