version: 2
jobs:
  build:

    working_directory: ~/drivebackup

    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          - CC_TEST_REPORTER_ID=ba673ad992797b6b9e954a03e011fa6769900530efb15ff00c7af89253b0d671
    steps:
      - checkout
      - run:
          name:  Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - restore_cache:
          key: drivebackup-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: drivebackup-{{ checksum "pom.xml" }}

      - type: shell
        command: |
          ./tmp/cc-test-reporter before-build
          mvn test
          ./.circleci/report_coverage $?

      - store_test_results:
          path: target/surefire-reports
